# Change these first
owner: sbsrubik # Your GitHub organization or username, where this repository lives
repo: server-uptime # The name of this repository

i18n:
  footer: 2021 Solid Block Studios

sites:
  - name: Forums
    url: https://titsrp.com
  - name: TitsRP Server
    icon: https://www.titsrp.com/images/Gmod-small.ico
    url: $TRP_SERVER
  - name: Rust Weekly
    icon: https://www.titsrp.com/images/rust_94773.ico
    url: $WEEKLY_SERVER
  - name: Rust Bi-Weekly
    icon: https://www.titsrp.com/images/rust_94773.ico
    url: $BIWEEKLY_SERVER
  - name: API Server
    url: $API_SERVER
    icon: https://www.titsrp.com/images/api_icon.svg
  - name: Boombox
    url: $MEDIA
    icon: https://www.titsrp.com/images/audio.svg

status-website:
  cname: status.titsrp.com
  logoUrl: https://forums.titsrp.com/uploads/monthly_2021_06/tits-logo-small.png.560dc95feed57a98ea80c06f01fd141a.png.6c5dc17eeb3b7ec22aad8c386b942694.png
  name: TitsRP/Tits.GG Server Status
  themeUrl: https://titsrp.com/images/tits.css
  favicon: https://titsrp.com/images/favicon.ico
  introTitle: "**Is TitsRP/Tits.GG down?** Check server status and uptime. 
  introMessage: Daily server resets and scheduled maintenance will not show servers as offline. If you cannot connect and there are no maintenance windows open, check Discord!
  navbar:
    - title: Forums
      href: https://forums.titsrp.com
    - title: Discord
      href: https://discord.gg/yceff7Bjh9
      

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
