# Change these first
owner: sbsrubik # Your GitHub organization or username, where this repository lives
repo: server-uptime # The name of this repository

i18n:
  footer: ""

sites:
  - name: Community Forums
    check: "tcp-ping"
    url: https://titsrp.com
    port: 443
  - name: TitsRP Server
    icon: https://www.titsrp.com/images/Gmod-small.ico
    check: "tcp-ping"
    url: $TRP_SERVER
    port: 443
  - name: Rust Weekly
    check: "tcp-ping"
    icon: https://www.titsrp.com/images/rust_94773.ico
    url: $WEEKLY_SERVER
    port: 443
  - name: Rust Bi-Weekly
    check: "tcp-ping"
    icon: https://www.titsrp.com/images/rust_94773.ico
    url: $BIWEEKLY_SERVER
    port: 443
  - name: API Server
    check: "tcp-ping"
    url: $API_SERVER
    icon: https://www.titsrp.com/images/api_icon.svg
    port: 443
  - name: Boombox
    check: "tcp-ping"
    url: $MEDIA
    icon: https://www.titsrp.com/images/audio.svg
    port: 443

status-website:
  cname: status.titsrp.com
  logoUrl: https://forums.titsrp.com/uploads/monthly_2021_06/tits-logo-small.png.560dc95feed57a98ea80c06f01fd141a.png.6c5dc17eeb3b7ec22aad8c386b942694.png
  name: Server Status
  themeUrl: https://titsrp.com/images/tits.css
  favicon: https://titsrp.com/images/favicon.ico
  introTitle: "**Is TitsRP down?** All times are in EDT"
  introMessage: If there is no maintenance window open and you still cannot connect, check Discord!
  navbar:
    - title: Forums
      href: https://forums.titsrp.com
    - title: Discord
      href: https://discord.gg/yceff7Bjh9
      

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
